server:
  port: 8081
auth:
  mock:
    issuer: http://localhost:8081
    redirect-ssr: http://localhost:8080/login/oauth2/code/ssr

spring:
  thymeleaf:
    cache: false

    # used by actuator info endpoint
info:
  app:
    name: OIDC Mock Server
    description: mock oidc for laa-claim-for-payment
    version: 1.0.0

management:
  server:
    base-path: /actuator
  # specify actuator endpoints to enable
  endpoints:
    web:
      exposure:
        include: health,info

  # show detailed health status
  endpoint:
    health:
      show-details: always

  info:
    env:
      enabled: true

  mock-oidc:
    client-secret: mock-secret
