logging.level.root: DEBUG
security:
  enabled: true   # feature-flag flip to true when the client is ready
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_BASE_URL:"https://laa-claim-for-payment-mock-oidc-uat.cloud-platform.service.justice.gov.uk"}
          audience: ${AUDIENCE:api-audience}