security:
  enabled: true 
logging.level:
  root: INFO
  # org.springframework.security.oauth2.jwt: DEBUG
  # org.springframework.security.oauth2.server.resource: DEBUG
  # org.springframework.security.web.access.ExceptionTranslationFilter: DEBUG
  org.springframework.security: DEBUG
  org.springframework.security.oauth2: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/8352c342-da15-413a-8b5b-d89545766f0c/v2.0
  flyway.locations: classpath:db/migration,classpath:db/local